CREATE TABLE IF NOT EXISTS Clients (
number_client INT PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
passport VARCHAR(255) NOT NULL,
datebirth DATE NOT NULL,
address VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);