CREATE TABLE IF NOT EXISTS Employeers (
id_employeer INT PRIMARY KEY NOT NULL,
post VARCHAR(255) NULL,
name VARCHAR(255) NULL,
login VARCHAR(255) NULL,
password VARCHAR(255) NULL,
lastLogIn VARCHAR(255) NULL,
StatusLogIn VARCHAR(255) NULL
);

