CREATE TABLE IF NOT EXISTS Clients (
name VARCHAR(255) NOT NULL,
number_client INT PRIMARY KEY auto_increment,
passport VARCHAR(255) NOT NULL,
datebirth VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);