CREATE TABLE IF NOT EXISTS Employeers (
id_employeer VARCHAR(255) PRIMARY KEY NOT NULL,
post VARCHAR(255) NULL,
name VARCHAR(255) NULL,
login VARCHAR(255) NULL,
password VARCHAR(255) NULL,
lastLogIn DATETIME NULL,
StatusLogIn VARCHAR(255) NULL
);

